name: Java App CI

on:
  push:
    branches:
      - main
    paths:
      - "java-app/**"
  pull_request:
    branches:
      - main
    paths:
      - "java-app/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-app

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        run: mvn clean verify
